```{r}
 # Libraries
library(dynamicTreeCut)
library(sparcl)
library(igraph)
library(cvxbiclustr)
library(tidyverse)
library(dbscan)
library(FNN)
```

```{r}
solve_alpha = function(A, lambda) {
  f = function(alpha) {
    s = sum(pmax(alpha / A - lambda, 0))
    return(s / 2 - 1)
  }
  a = uniroot(f, c(0.0, 1000.0), tol = 1e-10)$root
  return(a)
}


bcc_transpose = function(X, # Cluster the columns while reweighting them
                         lambda,
                         gamma = 1000,
                         k = 5,
                         tmax = 30,
                         w_0 = NA) {
  n = dim(X)[1]
  p = dim(X)[2]
  if(any(is.na(w_0))) {
    w = runif(p)
  } else{
    w = w_0
  }

  w = w / sum(w)
  col_sum_sq = numeric(p)
  M = X
  for (time in 1:tmax) {
    # scaled_columns = t(t(X) * sqrt(w^2 + lambda * w))  # Equivalent, may be faster in some cases
    scaled_columns = sweep(X, 2, sqrt(w^2 + lambda * w), "*")
    D = as.matrix(dist(t(scaled_columns))) ^ 2

    nn = matrix(0, p, k) # p x k  since weighting columns
    for (i in 1:p) {  # k+1 and filter out self assignment
      neighbors = k.nearest.neighbors(i, D, k+1)
      nn[i,] = neighbors[which(neighbors != i)][1:k]
    }
    W = matrix(0, p, p)
    for (i in 1:p) {
      W[i, nn[i,]] = exp(-0.5 * D[i, nn[i,]] / n)  # TODO replace 0.5 with phi
    }

    # https://stackoverflow.com/a/74645749
    W_sum_at_nn <- cbind(apply(nn, 2, function(z) {
      W[cbind(seq_along(z), z)] + W[cbind(z, seq_along(z))]
    }))
    
    numer_left <- gamma * sapply(1:p, function(m) {
      W_sum_at_nn[m,] %*% t(M[,nn[m,]])
    })
    numer_right = sweep(X, 2, w^2 + lambda * w, "*")

    denom_left = rowSums(W_sum_at_nn) * gamma
    denom_right = w^2 + lambda * w
    denom = denom_left + denom_right
    M = sweep(numer_left + numer_right, 2, denom, "/")
    M[, which(w <= 0)] = 0

    col_sum_sq = colSums((X - M)^2)
    alpha = solve_alpha(col_sum_sq, lambda)
    w = pmax(alpha / col_sum_sq - lambda, 0) / 2
  }
  return(list(M=M, w=w))
}

bcc = function(X,
               lambda,
               gamma = 1000,
               k = 5,
               tmax = 30,
               w_0 = NA) {
  n = dim(X)[1]
  p = dim(X)[2]
  if(any(is.na(w_0))) {
    w = runif(p)
  } else{
    w = w_0
  }

  w = w / sum(w)
  col_sum_sq = numeric(p)
  M = X
  for (time in 1:tmax) {
    # scaled_columns = t(t(X) * sqrt(w^2 + lambda * w))  # Equivalent, may be faster in some cases
    scaled_columns = sweep(X, 2, sqrt(w^2 + lambda * w), "*")
    D = as.matrix(dist(scaled_columns)) ^ 2

    nn = matrix(0, n, k) # n x k
    for (i in 1:n) {  # k+1 and filter out self assignment
      neighbors = k.nearest.neighbors(i, D, k+1)
      nn[i,] = neighbors[which(neighbors != i)][1:k]
    }
    W = matrix(0, n, n)
    for (i in 1:n) {
      W[i, nn[i,]] = exp(-0.5 * D[i, nn[i,]] / p)
    }

    # https://stackoverflow.com/a/74645749
    W_sum_at_nn <- cbind(apply(nn, 2, function(z) {
      W[cbind(seq_along(z), z)] + W[cbind(z, seq_along(z))]
    }))

    numer_left <- gamma * t(sapply(1:n, function(m) {
      W_sum_at_nn[m,] %*% M[nn[m,],]
    }))
    numer_right = sweep(X, 2, w^2 + lambda * w, "*")

    denom_left = rowSums(W_sum_at_nn) * gamma
    denom_right = w^2 + lambda * w
    denom = outer(denom_left, denom_right, "+")
    
    M = (numer_left + numer_right) / denom
    M[, which(w <= 0)] = 0

    col_sum_sq = colSums((X - M)^2)
    alpha = solve_alpha(col_sum_sq, lambda)
    w = pmax(alpha / col_sum_sq - lambda, 0) / 2
  }
  return(list(M=M, w=w))
}
```

```{r}
X = read.csv('movement_libras.csv', head = FALSE)
X = data.matrix(X)
toss = X[, 91]
X = X[, -91]
I3 = which(toss == 3)
I4 = which(toss == 4)
I5 = which(toss == 5)
I7 = which(toss == 7)
I11 = which(toss == 11)
I12 = which(toss == 12)
I = c(I3, I4, I5, I7, I11, I12)
X = X[I, ]
toss = toss[I]
p = dim(X)[2]
for (i in 1:p) {
  X[, i] = (X[, i] - mean(X[, i])) / sd(X[, i])
}
```


```{r}
# profvis::profvis({
# }
# )
# l=bcc(X,lambda=0.002,gamma=10,tmax=100)

```

```{r}
# h = hclust(dist(l[[1]]), method = 'average')
# cut_result = cutreeDynamic(h, distM = as.matrix(dist(l[[1]])))
```


```{r}
# compare(toss, cut_result, 'adjusted.rand')
# compare(toss, cut_result, 'nmi')

```


```{r}

bicobra <- function(X, lambda, gamma, k, tmax) {
  n = dim(X)[1]
  p = dim(X)[2]
  U = X
  P = matrix(0, nrow=n, ncol=p)
  Q = matrix(0, nrow=p, ncol=n)
  w <- runif(p)
  w <- w/sum(w)

  for(t in 1:tmax) {
    # Do regular bcc
    bcc_1 = bcc(U + P, lambda=lambda, gamma=gamma, k=k, tmax=tmax, w_0 = w)
    Y = bcc_1$M
    w = bcc_1$w
    P = U + P - Y
    # Do transposed bcc
    bcc_2 = bcc_transpose(Y + t(Q), lambda=lambda, gamma=gamma, k=k, tmax=tmax, w_0 = w)
    U = bcc_2$M
    w = bcc_2$w
    Q = t(Y) + Q - t(U)
  }
  
  return(list(U=U, Y=Y, w=w))
}
```


```{r}
# lb=bicobra(X,lambda=0.002,k=5,gamma=10,tmax=20)
```


```{r}

solve_alpha_prox = function(D_l, nu, q, lambda) {
  D_nu = D_l / (1/nu + D_l)
  f = function(alpha) {
    s = sum(D_nu * pmax((alpha + q/nu) / D_l - lambda/2, 0))
    return(s - 1)
  }
  a = uniroot(f, c(-min(q/nu), 10000.0), tol = 1e-8)$root
  return(a)
}

create_edge_incidence_edges <- function(P,n) {
  nEdges <- nrow(P)
  E <- Matrix(data=0,nrow=nEdges,ncol=n,sparse=TRUE)
  r <- 1:nEdges
  col <- P[,1]
  E[(col-1)*nEdges + r] <- 1
  c <- P[,2]
  E[(col-1)*nEdges + r] <- -1
  return(E)
}


fast_gkn_weights <- function(X, k_row, k_col, phi, approx=0) {
  p <- ncol(X)
  n <- nrow(X)

  all_row_knn <- kNN(X, k_row, sort=FALSE, approx=approx)
  all_col_knn <- kNN(t(X), k_col, sort=FALSE, approx=approx)
  
  # all_row_knn <- FNN::get.knn(X, k_row, algorithm="cover_tree")
  # all_col_knn <- FNN::get.knn(t(X), k_col, algorithm="cover_tree")
  unique_row_edges <- data.frame(all_row_knn$id) |>
    mutate(index=row_number()) |>
    pivot_longer(!index) |>
    mutate(neighbor_index=as.integer(str_remove(name, "X")),
           from_node=pmin(index, value),
           to_node=pmax(index, value)) |>
    distinct(from_node, to_node, .keep_all = TRUE)

  unique_col_edges <- data.frame(all_col_knn$id) |>
    mutate(index=row_number()) |>
    pivot_longer(!index) |>
    mutate(neighbor_index=as.integer(str_remove(name, "X")), 
           from_node=pmin(index, value),
           to_node=pmax(index, value)) |>
    distinct(from_node, to_node, .keep_all = TRUE)
  
  # Need to fix this to only sum over edges used
  all_row_dist <- all_row_knn$dist[
    cbind(unique_row_edges$from_node, 
          unique_row_edges$neighbor_index)]
  all_col_dist <- all_col_knn$dist[
    cbind(unique_col_edges$from_node, 
          unique_col_edges$neighbor_index)]
  
  row_weights <- exp(- all_row_dist^2 * phi / p)
  row_weights <- row_weights / sum(row_weights) / sqrt(p)
  col_weights <- exp(- all_col_dist^2 * phi / n)
  col_weights <- col_weights / sum(col_weights) / sqrt(n)

  # Construct edge-incidence matrices
  E_row <- create_edge_incidence_edges(
    cbind(unique_row_edges$from_node, unique_row_edges$to_node), n)
  E_col <- create_edge_incidence_edges(
    cbind(unique_col_edges$from_node, unique_col_edges$to_node), p)

  return(list(w_row = row_weights, w_col = col_weights, E_row = E_row, E_col = E_col))
}

rscobra <- function(X, lambda, k_row=4, k_col=4, nu=1, gamma=10, phi=0.05,
                    tmax=100, tol=1e-9, recalculate_weights=TRUE, approx=0,
                    progress=TRUE) {
  n = dim(X)[1]
  p = dim(X)[2]
  Q <- X
  q <- runif(p)
  q <- q/sum(q)
  pb = txtProgressBar(min = 0, max = tmax, initial = 0) 
  for(t in 1:tmax) {
    # Should recalculation use new weight vector? 
    if(recalculate_weights || t==1) {
      # wts = gkn_weights(t(Q), k_row=k_row, k_col=k_col, phi=phi, return_connectivity=FALSE)
      wts = fast_gkn_weights(t(Q), k_row=k_row, k_col=k_col, phi=phi, approx=approx)
      w_row <- wts$w_row
      w_col <- wts$w_col
      E_row <- wts$E_row
      E_col <- wts$E_col
    }

    # Cobra has rows as features, columns as samples
    cobra_result <- cobra(t(Q), E_row, E_col, w_row, w_col, gamma=gamma, max_iter=tmax)

    if(sum((t(cobra_result$U[[1]]) - Q)^2) < tol) {
       Q <- t(cobra_result$U[[1]])
       break
    }
    
    Q <- t(cobra_result$U[[1]])
    for(t2 in 1:tmax) {  # Coordinate wise minima of biconvex optimization
      # Solve for Q with fixed w
      w_sq <- q^2 + lambda * q
      X_weighted <- sweep(X, 2, w_sq / (1/nu + w_sq), "*")
      Q_weighted <- sweep(Q, 2, 1 / (1 + nu * w_sq), "*")
      Q <- Q_weighted + X_weighted
      
      # Solve for w with fixed U
      col_sum_sq = colSums((X - Q)^2)
      alpha = solve_alpha_prox(col_sum_sq, nu, q, lambda)
      new_q = (col_sum_sq) / (col_sum_sq + 1/nu) * pmax((alpha + q/nu) / col_sum_sq - lambda/2, 0)
      
      if(sum((new_q - q)^2) < tol) {
        q = new_q
        break
      }
      q = new_q
    }
    setTxtProgressBar(pb,t)
  }
  close(pb)

  return(list(U=Q, w=q, lambda=lambda))
}
```

```{r}
lrs=rscobra(X, lambda=0.05,k_col=2, k_row=2,nu=0.5, gamma=1000, tmax=100, phi=0.5, recalculate_weights = TRUE, tol=1e-6)

```

```{r}
X2 = read.csv('lung500.csv', head = FALSE)
X2 = scale(data.matrix(X2))

```

```{r}
# l=rscobra(X2, lambda=0.2,k_col=5,nu=0.5, gamma=100,tmax=200, phi=0.5, recalculate_weights = TRUE, tol=1e-6)

profvis::profvis({
  l=rscobra(lym, lambda=0.2,k_col=5,nu=0.5, gamma=100,tmax=100, phi=0.5, 
            recalculate_weights = TRUE, tol=1e-6, approx=0.1)
})

```

```{r}
mat_df <- function(bcbc_result, cluster_w_weights=TRUE, filter_weight=-Inf, lambda=1) {
    df <- as.data.frame(bcbc_result$U) |>
      mutate(row_num = row_number()) |>
      pivot_longer(!row_num, names_to="col_num") |>
      mutate(col_num = as.numeric(str_replace(col_num, "V", "")),
             weight = rep(bcbc_result$w, max(row_num))) |>
      filter(weight > filter_weight)
    
    w_prime_idx <- which(bcbc_result$w > filter_weight)
    w_prime <- bcbc_result$w[w_prime_idx]
    U_prime <- bcbc_result$U[, w_prime_idx]
    # TODO should row dist be weighted?
    if(cluster_w_weights) {
      w_vals = sqrt(w_prime + lambda * w_prime)
      solution_mat = sweep(U_prime, 2, w_vals, "*")
    } else {
      solution_mat <- U_prime
    }
    row_dist <- dist(solution_mat)
    col_dist <- dist(t(solution_mat))
  
    h_row <- hclust(row_dist)
    h_col <- hclust(col_dist)
    df <- df |>
      inner_join(tibble(row_num=h_row$order, order_row=1:length(h_row$order))) |>
      inner_join(tibble(col_num=h_col$order, order_col=1:length(h_col$order)))
    
    df
}

plot_matrix <- function(from_mat_df) {
  ggplot(from_mat_df, aes(x=order_col, y=order_row, fill=value)) +
    geom_raster() +
    scale_fill_gradient2() +
    theme_minimal() +
    theme(
      axis.text.x=element_blank(), 
      axis.ticks.x=element_blank()
    )
}

```

```{r}
lym <- t(read.csv("./lymphoma.x.txt", header=FALSE, sep=" "))
lym <- scale(lym)
lym_results2 <- rscobra(lym, lambda=0.005, k=4, nu=1, gamma=500, phi=0.5, tmax=20, tol=1e-6)

```

```{r}

get_num_clusters <- function(d_mat, cluster_threshold) {
  h <- hclust(d_mat)
  return(sum(h$height > max(d_mat) * cluster_threshold))
}

get_cv_metrics <- function(X, bcbc_run, weighted_clusters=TRUE, cluster_threshold=0.05) {
  U <- bcbc_run$U
  w <- bcbc_run$w
  lambda <- bcbc_run$lambda
  n <- nrow(X)
  p <- ncol(X)
  swept <- sweep(U, 2, w^2 + lambda * w, "*")
  rss <- sum(sweep(X - U, 2, w^2 + lambda * w, "*")^2)
  if(weighted_clusters) {
    row_d_mat <- dist(swept)
    col_d_mat <- dist(t(swept))
  } else {
    row_d_mat <- dist(U)
    col_d_mat <- dist(t(U))
  }
  num_row_clusters <- get_num_clusters(row_d_mat, cluster_threshold)
  num_col_clusters <- get_num_clusters(col_d_mat, cluster_threshold)

  # TODO should this include lambda?
  sparsity_measure <- sum(w^2)^2 / sum(w^4)
  return(list(
    eBIC = n * p * log(rss / (n * p)) + 2 * log(n * p) * (num_row_clusters + num_col_clusters + sparsity_measure),
    BIC1 = n * p * (log(rss) + sum(abs(swept) > 1e-12)),
    num_row_clusters = num_row_clusters,
    num_col_clusters = num_col_clusters,
    sparsity = sparsity_measure,
    rss = rss)
  )
}

tune_rscobra <- function(X, lambdas=c(1), k_rows=c(2), k_cols=c(2),
                         nus=c(1), gammas=c(1),
                         tmaxs=c(100), phis=c(0.5), recalculate_weights=c(TRUE), tols=c(1e-6),
                         weighted_clusters=TRUE, cluster_threshold=c(0.01)) {
  all_params <- expand.grid(lambda=lambdas, k_row=k_rows, k_col=k_cols,
                            nu=nus, gamma=gammas, tmax=tmaxs, phi=phis,
                            recalculate_weights=recalculate_weights, tol=tols)
  
  cv_data <- data.frame(all_params)

  all_runs <- list()
  for(param_set in 1:nrow(all_params)) {
    params <- all_params[param_set, ]
    result <- rscobra(X,
                      lambda=params$lambda,
                      k_row=params$k_row,
                      k_col=params$k_col,
                      nu=params$nu,
                      gamma=params$gamma,
                      tmax=params$tmax,
                      phi=params$phi,
                      recalculate_weights=params$recalculate_weights,
                      tol=params$tol)
    cv_metrics <- get_cv_metrics(X, result, weighted_clusters = weighted_clusters,
                                 cluster_threshold = cluster_threshold)
    
    # holdout <- get_holdoutmetrics(X, TRUE)

    cv_data[param_set, names(cv_metrics)] <- cv_metrics
    all_runs[[param_set]] <- result
  }
  return(list(all_runs = all_runs, cv_data = cv_data))
}

```

```{r}
X2 = read.csv('lung100.csv', head = FALSE)
X2 = scale(data.matrix(X2))

cv_lym <- tune_rscobra(X2, lambdas=c(0.001, 0.01, 0.1), nus=c(0.001, 0.01, 0.1), gammas=c(10, 100, 1000))

```


```{r}
gen_checkerboard <- function(n, p, num_row_clusters, num_col_clusters, p_extra=0, noise=1) {
  row_partition <- sample(1:num_row_clusters, n, replace=TRUE)
  col_partition <- sample(1:num_col_clusters, p, replace=TRUE)
  mu_kr <- matrix(runif(num_row_clusters * num_col_clusters, -2, 2),
                  nrow=num_row_clusters,
                  ncol=num_col_clusters
                  )
  
  data_mat <- matrix(NA, nrow=n, ncol=(p+p_extra))
  for(i in 1:n) {
    for(j in 1:p) {
      data_mat[i, j] <- rnorm(1, mean=mu_kr[row_partition[i], col_partition[j]],
                              sd=noise)
    }
  }
  data_mat[, (p+1):(p + p_extra)] <- rnorm(n * p_extra, mean=0, sd=noise)
  
  shuffled_col <- data_mat[, sample(p+p_extra)]
  shuffled_row <- shuffled_col[sample(n), ]
  return(scale(shuffled_row))
}


```

```{r}
checker <- gen_checkerboard(100, 200, 5, 10, 300, 1)
rs_checker <- tune_rscobra(checker,
                           lambdas=c(0.001, 0.01, 0.1),
                           nus=c(0.001, 0.01, 0.1),
                           gammas=c(10, 100, 1000))

```
