```{r}
source("./RSCobra.R")
# devtools::install_github("cran/cvxclustr")
library(cvxclustr)
library(MASS)
```

# Helper Functions 

```{r}

mat_df <- function(matrix, labels=NULL, weights=c(), lambda=0, filter_weight=0,
                    cluster_with_weights=TRUE) {
  if(length(weights) > 0) {
      valid_weights <- which(weights > filter_weight)
      weights <- weights[valid_weights]
      matrix <- matrix[, valid_weights]
  }
  df <- as.data.frame(matrix) |>
    mutate(row_num = row_number()) |>
    pivot_longer(!row_num, names_to = "col_num") |>
    mutate(col_num = as.numeric(str_replace(col_num, "V", "")))

  if(length(weights > 0) && cluster_with_weights) {
    w_vals = sqrt(weights^2 + lambda * weights)
    matrix <- sweep(matrix, 2, w_vals, "*")
  }

  row_dist <- dist(matrix)
  col_dist <- dist(t(matrix))
  
  h_row <- hclust(row_dist)
  h_col <- hclust(col_dist)
  df <- df |>
    inner_join(tibble(
      row_num = h_row$order,
      order_row = 1:length(h_row$order)
    )) |>
    inner_join(tibble(
      col_num = h_col$order,
      order_col = 1:length(h_col$order)
    ))

  if (is.null(labels)) {
    return(df)
  } else {
    df <- df |>
      inner_join(tibble(row_num = 1:length(h_row$order), label = labels))
  }
  df
}

# checker <- gen_checkerboard(6, 40, 2, 2, noise=1, shuffle = TRUE)
# 
# ggplot(mat_df(checker$X), aes(x = order_col, y = order_row)) +
#     geom_raster(aes(fill = value)) +
#     scale_fill_gradient2() +
#     theme_minimal() +
#     theme(axis.text.x = element_blank(),
#           axis.ticks.x = element_blank())

# X <- t(checker$X)
# 
# w <- kernel_weights(X, 0.5)
# w <- knn_weights(w, 2, ncol(X))
# # 
# gammas <- c(100, 1000, 10000)
# # 
# solutions <- cvxclust_path_admm(X, w, gammas, nu=1)
```

# Convex Clustering Examples

```{r}


per_cluster <- 30
num_solutions <- 9

set.seed(2)
X <- rbind(
  mvrnorm(per_cluster, c(1,1), matrix(c(1, 0.5, 0.5, 1), nrow=2)),
  mvrnorm(per_cluster, c(-2.25,1), matrix(c(0.75, 0.5, 0.5, 0.75), nrow=2)),
  mvrnorm(per_cluster, c(0,-1.75), matrix(c(1.5, 0, 0, 0.25), nrow=2))
)

X <- t(X)

w <- kernel_weights(X, 0.5)
w <- knn_weights(w, 3, ncol(X))

gammas <- c(0.1, 1, 2, 5, 10, 20, 35, 50, 100)

solutions <- cvxclust_path_admm(X, w, gammas)

to_plot <- tibble(
  orig_x = numeric(),
  orig_y = numeric(),
  new_x = numeric(),
  new_y = numeric(),
  gamma = numeric(),
  index = numeric(),
  true_cluster = numeric(),
)

for(i in 1:num_solutions) {
  to_plot <- rbind(
    to_plot,
    tibble(
      orig_x = X[1,],
      orig_y = X[2,],
      new_x = solutions$U[[i]][1,],
      new_y = solutions$U[[i]][2,],
      gamma = rep(gammas[i], ncol(X)),
      index = 1:ncol(X),
      true_cluster = rep(c(1, 2, 3), times = 1, each = per_cluster),
    )
  )
}
```

```{r}

custom_labeller <- function(variable, value) {
  return(paste0("gamma=", value))
}

ggplot(to_plot) +
  geom_point(aes(orig_x, orig_y), alpha=0.25) +
  geom_segment(aes(group=index, x=orig_x, y=orig_y, xend=new_x, yend=new_y), 
               alpha=0.25, linetype=2) +
  geom_point(aes(new_x, new_y), color="blue") +
  facet_wrap(~gamma, labeller=custom_labeller) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank()
  )

```

```{r}
gammas <- seq(0, 100, 0.25)

num_solutions <- length(gammas)
solutions <- cvxclust_path_admm(X, w, gammas)

to_plot <- tibble(
  orig_x = numeric(),
  orig_y = numeric(),
  new_x = numeric(),
  new_y = numeric(),
  gamma = numeric(),
  index = numeric(),
  true_cluster = numeric(),
)

for(i in 1:num_solutions) {
  to_plot <- rbind(
    to_plot,
    tibble(
      orig_x = X[1,],
      orig_y = X[2,],
      new_x = solutions$U[[i]][1,],
      new_y = solutions$U[[i]][2,],
      gamma = rep(gammas[i], ncol(X)),
      index = 1:ncol(X),
      true_cluster = rep(c(1, 2, 3), times = 1, each = per_cluster),
    )
  )
}

```

```{r}
ggplot(to_plot) +
  geom_point(aes(orig_x, orig_y), alpha=0.15) +
  geom_path(aes(group=index, x=new_x, y=new_y, color=as.character(true_cluster)), 
               alpha=0.25, linetype=2) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank()
  ) +
  guides(color = "none") +
  ggtitle("Convex clustering solution path for 3 clusters")

```

# Biclustering Example

```{r}
checker <- gen_checkerboard(300, 300, 10, 10, noise=1.5, shuffle = TRUE, prob_empty = 0.5, scale=FALSE)

ggplot(mat_df2(checker$X), aes(x = order_col, y = order_row)) +
    geom_raster(aes(fill = value)) +
    scale_fill_gradient2() +
    theme_minimal() +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank())

from_palm3 <- tune_bcbc(checker$X, model=palm, lambdas=c(0), gammas=2^seq(10, 15, 0.5), recalculate_weights = TRUE, progress = TRUE)
```

# Clustering Dimension

```{r}
set.seed(20)
check <- gen_checkerboard(100, 200, 4, 4, noise=2, p_extra=0, scale=FALSE)

all_checks <- list()
all_checks[[1]] <- cbind(check$X,
                         matrix(rnorm(100*100, sd=2), nrow=100))
for(i in 2:10) {
  all_checks[[i]] <- cbind(all_checks[[i-1]],
                           matrix(rnorm(100*100, sd=2), nrow=100))
}

plot_fit(mat_df(check$X, check$row_partition)) / 
  plot_fit(mat_df(all_checks[[1]], check$row_partition)) / 
  plot_fit(mat_df(all_checks[[2]], check$row_partition)) /
  plot_fit(mat_df(all_checks[[3]], check$row_partition)) /
  plot_fit(mat_df(all_checks[[4]], check$row_partition))

check_sol <- palm(check$X, lambda = 0, gamma = 1000)
check_sol100 <- palm(all_checks[[1]], lambda = 0.055, gamma = 1500)
check_sol200 <- palm(all_checks[[2]], lambda = 0.075, gamma = 2000)
check_sol300 <- palm(all_checks[[3]], lambda = 0.090, gamma = 2500)
check_sol400 <- palm(all_checks[[4]], lambda = 0.100, gamma = 3000)

plot_fit(
  mat_df(
    check_sol$U,
    weights = check_sol$w,
    labels = check$row_partition,
    lambda = 0,
    cluster_with_weights = FALSE
  )
) /
  plot_fit(
    mat_df(
      check_sol100$U,
      weights = check_sol100$w,
      labels = check$row_partition,
      lambda = 0.055,
      cluster_with_weights = FALSE
    )
  ) /
  plot_fit(
    mat_df(
      check_sol200$U,
      weights = check_sol200$w,
      labels = check$row_partition,
      lambda = 0.075,
      cluster_with_weights = FALSE
    )
  ) /
  plot_fit(
    mat_df(
      check_sol300$U,
      weights = check_sol300$w,
      labels = check$row_partition,
      lambda = 0.090,
      cluster_with_weights = FALSE
    )
  ) /
  plot_fit(
    mat_df(
      check_sol400$U,
      weights = check_sol400$w,
      labels = check$row_partition,
      lambda = 0.100,
      cluster_with_weights = FALSE
    )
  )
```



# PALM data

```{r}

num_iters = 20
x = rep(NA, num_iters)
x[1] = 0.1
x_grad = rep(0, num_iters)
y = rep(NA, num_iters)
y[1] = 0.15
y_grad = rep(0, num_iters)

prox <- function(input, nu, offset = 1) {
  if(input > offset + nu) {
    return(input - nu)
  } else if(input < nu - offset){
    return(input + nu)
  }
  return(offset)
}

for(i in 2:num_iters) {
  lip_y =  (y[i - 1] ^ 2 + 0.25)
  x_grad[i] = x[i - 1] -  2 * x[i - 1] * lip_y
  x[i] = prox(x_grad[i], 1)
  
  lip_x =  (x[i] ^ 2 + 0.25)
  y_grad[i] = y[i - 1] -  2 * y[i - 1] * lip_x
  y[i] = prox(y_grad[i], 1)
}

```



# Contour Plots

```{r}
coordinate_wise_minima <- function(fixed) {
  opt <- rep(NA, length(fixed))
  for(i in seq_along(fixed)) {
    f <- function(x) {
      (x ^ 2 + 1 / 4) * (fixed[i] ^ 2 + 1 / 4) + abs(x - 1) + abs(fixed[i] - 1)
    }
    opt[i] <- optim(1, f, method="Brent", lower=-10, upper=10)$par
  }
  cbind(fixed, opt)
}

coordinate_wise_palm_minima <- function(fixed) {
  opt <- rep(NA, length(fixed))
  for(i in seq_along(fixed)) {
    f <- function(x) {
      lip =  (fixed[i] ^ 2 + 0.25)
      (x - prox(x, x - 2 * x * lip))^2
    }
    opt[i] <- optim(1, f, method="Brent", lower=-2, upper=2)$par
  }
  cbind(fixed, opt)
}

```


```{r}
x1 <- seq(0.1, 1.1, 0.005)
x2 <- seq(0.1, 1.1, 0.005)

biconvex_func <- function(x, y) {
  (x ^ 2 + 1 / 4) * (y ^ 2 + 1 / 4) + abs(x - 1) + abs(y - 1)
}

minima_curves <- as.data.frame(coordinate_wise_palm_minima(seq(0.1, 1.1, 0.01)))

expand.grid(X1 = x1, X2 = x2) |>
  mutate(Z = biconvex_func(X1, X2)) |>
  ggplot() +
  geom_contour(aes(X1, X2, z = Z)) +
  geom_contour_filled(
    aes(X1, X2, z = Z),
    colour="black",
    breaks = c(
      seq(1.11, 1.2, 0.01),
      seq(1.25, 1.4, 0.05),
      seq(1.5, 2, .1)),
    alpha=0.85
  ) +
  geom_path(data=minima_curves, mapping=aes(fixed, opt), color="cyan", linetype=1, linewidth=1.1) +
  geom_path(data=minima_curves, mapping=aes(opt, fixed), color="green", linetype=1, linewidth=1.1) +
  scale_fill_viridis_d(option="C") +
  guides(fill="none") +
  theme_minimal() +
  scale_x_continuous(breaks=seq(0.1, 1.1, 0.1)) + 
  scale_y_continuous(breaks=seq(0.1, 1.1, 0.1)) + 
  xlab("x") + 
  ylab("y")

```


# Real Data

```{r}
plot_fit <- function(plot_df, title="") {
  ggplot(plot_df, aes(x = order_col, y = order_row)) +
    geom_raster(aes(fill = value)) +
    annotate(
      geom = "rect",
      xmin = -max(plot_df$order_col) / 25,
      xmax = 0,
      ymin = plot_df$order_row - 0.5,
      ymax = plot_df$order_row + 0.5,
      fill = case_when(
        plot_df$label == 1 ~ "green",
        plot_df$label == 2 ~ "yellow",
        plot_df$label == 3 ~ "purple",
        plot_df$label == 4 ~ "grey",
        plot_df$label == 5 ~ "orange",
        plot_df$label == 6 ~ "blue",
        plot_df$label == 7 ~ "red",
        plot_df$label == 8 ~ "magenta",
        plot_df$label == 9 ~ "pink",
        TRUE ~ "black"
      )
    ) +
    scale_fill_gradient2() +
    theme_minimal() +
    theme(
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      plot.title = element_text(size=30)
    ) +
    guides(fill = "none") +
    # xlab("Genes") +
    # ylab("Samples") +
    ggtitle(title)
}

```

## Leuk

```{r}
sparsebc_leuk <- readRDS("./sparsebc_leuk.RDS")
palm_leuk <- readRDS("./palm_leuk3.RDS")
cobra_leuk <- readRDS("./cobra_2leuk.RDS")

leuk_y <- read.csv("./data/leukemia.y.txt", header = FALSE)
leuk <- t(read.csv("./data/leukemia.x.txt", header = FALSE, sep = " "))
leuk <- scale(leuk)
```

```{r}
leuk_dist <- dist(leuk)
leuk_dist_col <- dist(t(leuk))

cut_tree_leuk <-
  cutreeDynamic(hclust(leuk_dist),
                minClusterSize = 9,
                distM = as.matrix(leuk_dist))

cut_tree_leuk_col <-
  cutreeDynamic(hclust(leuk_dist_col),
                minClusterSize = 20,
                distM = as.matrix(leuk_dist_col))

igraph::compare(cut_tree_leuk,
                leuk_y$V1,
                method="adjusted.rand")

plot_fit(mat_df(leuk, leuk_y$V1), "Gene Expression Pattern of Leukemia Samples")
```

```{r}

igraph::compare(palm_leuk$row_clusters[[157]],
                leuk_y$V1,
                method="adjusted.rand")

plot_fit(
  mat_df(
    palm_leuk$all_runs[[157]]$U,
    leuk_y$V1,
    weights = palm_leuk$all_runs[[157]]$w,
    cluster_with_weights = TRUE
  ),
  "Biclustering of Leukemia Data (BCBC)"
)
```

```{r}

igraph::compare(sparsebc_leuk$Cs,
                leuk_y$V1,
                method="adjusted.rand")

plot_fit(mat_df(sparsebc_leuk$mus,
                leuk_y$V1),
         "Biclustering of Leukemia Data (SparseBC)")
```

```{r}
igraph::compare(cobra_leuk$groups_col[[93]]$cluster,
                leuk_y$V1,
                method="adjusted.rand")

plot_fit(mat_df(t(cobra_leuk$U[[93]]),
                leuk_y$V1),
         "Biclustering of Leukemia Data (COBRA)")
```

## Lym

```{r}
# sparsebc_lym <- readRDS("./sparsebc_lym.RDS")
# palm_lym <- readRDS("./palm_lym_tuned3.RDS")
cobra_lym <- readRDS("./cobra_lym.RDS")

lym_y <- read.csv("./data/lymphoma.y.txt", header = FALSE)
lym <- t(read.csv("./data/lymphoma.x.txt", header = FALSE, sep = " "))
lym <- scale(lym)
```

```{r}

lym_dist <- dist(lym)
lym_dist_col <- dist(t(lym))

cut_tree_lym <-
  cutreeDynamic(hclust(lym_dist),
                minClusterSize = 9,
                distM = as.matrix(lym_dist))

cut_tree_lym_col <-
  cutreeDynamic(hclust(lym_dist_col),
                minClusterSize = 20,
                distM = as.matrix(lym_dist_col))

igraph::compare(cut_tree_lym,
                lym_y$V1,
                method="adjusted.rand")

plot_fit(mat_df(lym, lym_y$V1),
         "Gene Expression Pattern of Lymphoma Samples")
```

```{r}
igraph::compare(palm_lym$row_clusters[[86]],
                lym_y$V1,
                method="adjusted.rand")

plot_fit(
  mat_df(
    palm_lym$all_runs[[86]]$U,
    labels = lym_y$V1,
    cluster_with_weights = TRUE,
    weights = palm_lym$all_runs[[86]]$w
  ),
  "Biclustering of Lymphoma Data (BCBC)"
)
```

```{r}
igraph::compare(cobra_lym$groups_col[[44]]$cluster,
                lym_y$V1,
                method="adjusted.rand")

plot_fit(mat_df(t(cobra_lym$U[[44]]),
         lym_y$V1),
         "Biclustering of Lymphoma Data (COBRA)")
```

```{r}
igraph::compare(sparsebc_lym$Cs,
                lym_y$V1,
                method="adjusted.rand")

plot_fit(mat_df(
  sparsebc_lym$mus,
  lym_y$V1),
  "Biclustering of Lymphoma Data (SparseBC)")
```


## Colon

```{r}

colon_y <- read.csv("./data/colon.y.txt", header = FALSE)
colon <- t(read.csv("./data/colon.x.txt", header = FALSE, sep = " "))
colon <- scale(colon)
```

```{r}
plot_fit(colon, colon_y$V1, "Gene Expression Pattern of ... Samples")
```

## Prostate

```{r}

prostate_y <- read.csv("./data/prostate.y.txt", header = FALSE)
prostate <- t(read.csv("./data/prostate.x.txt", header = FALSE, sep = " "))
prostate <- scale(prostate)
```

```{r}
plot_fit(prostate, prostate_y$V1, "Gene Expression Pattern of ... Samples")
```

## SRBCT

```{r}

srbct_y <- read.csv("./data/srbct.y.txt", header = FALSE)
srbct <- t(read.csv("./data/srbct.x.txt", header = FALSE, sep = " "))
srbct <- scale(srbct)
```

```{r}
plot_fit(srbct, srbct_y$V1, "Gene Expression Pattern of ... Samples")
```

## Brain

```{r}

brain_y <- read.csv("./data/brain.y.txt", header = FALSE)
brain <- t(read.csv("./data/brain.x.txt", header = FALSE, sep = " "))
brain <- scale(brain)
```

```{r}
plot_fit(brain, brain_y$V1, "Gene Expression Pattern of ... Samples")
```