```{r}
library(tidyverse)

f <- function(x) {
  x^2 + 1/4 + abs(x-1)
}

add_quad <- function(f, t, x0) {
  function(x) {
    f(x) + 1/(2*t) * (x - x0)^2
  }
}


prox <- function(f, t, x0) {
  f_prime <- add_quad(f, t, x0)
  optim(0,
        f_prime,
        method = "Brent",
        lower = -2,
        upper = 2)$par
}

x_points <- seq(-1, 2, 0.01)

true_func <- tibble(
  x=seq(-1, 2, 0.01),
  y=f(x_points))

prox_funcs <- tibble(
  x = numeric(),
  y = numeric(),
  x0 = numeric(),
  t = numeric()
)

minima <- tibble(x0 = numeric(), t=numeric(), x_min = numeric(), y_quad=numeric(), func_val=numeric())

for (x0 in seq(-1, 2, 0.1)) {
  for (t in seq(0.05, 0.65, length.out=4)) {
    quad <- add_quad(f, t, x0)
    new_func <- tibble(
      x = x_points,
      y = quad(x_points),
      x0 = rep(x0, length(x_points)),
      t = rep(t, length(x_points))
    )
    prox_funcs <- rbind(prox_funcs, new_func)
    prox_val <- prox(f, t, x0)
    minima <- minima |> add_row(
      x0=x0, t=t, x_min=prox_val, y_quad=quad(prox_val),
      func_val=f(x0)
    )
  }
}
```

```{r}

custom_labeller <- function(variable, value) {
  return(paste0("nu=", value))
}

ggplot() +
  geom_line(
    data = prox_funcs,
    aes(x = x, y = y, group = x0),
    alpha = 0.3,
    color = "gray",
    linetype = 1
  ) +
  geom_line(data = true_func, aes(x = x, y = y)) +
  geom_line(
    data = minima,
    aes(x = x_min, y = y_quad),
    linetype = 1,
    color = "blue"
  ) +
  geom_segment(
    data = minima,
    aes(
      x = x0,
      xend = x_min,
      y = func_val,
      yend = y_quad,
      group = x0
    ),
    linetype = 2,
    color = "red",
    alpha = 0.5
  ) +
  facet_wrap(~t, labeller=custom_labeller) + 
  coord_cartesian(ylim = c(0.75, 5)) +
  theme_minimal()
```

```{r}

ggplot() +
  geom_line(
    data = minima,
    aes(x = x0, y = x_min),
    linetype = 1,
    color = "blue"
  ) +
  facet_wrap(~t, labeller=custom_labeller) + 
  theme_minimal()

```
