```{r}
library(tidyverse)
library(BCBC)
library(dynamicTreeCut)
library(sparseBC)
library(s4vd)
library(biclust)
library(SCBiclust)
library(future.apply)

# install.packages("../BCEL", repos = NULL, type="source")
library(BCEL)  # https://github.com/SamGRosen/BCEL/tree/master/BCEL/R, need to compile from source

plan(sequential, split=TRUE)
```

# Helper Functions

```{r}
metrics <- c("vi", "nmi", "split.join", "rand", "adjusted.rand")

overlap_to_groups <- function(row_memberships, col_memberships) {
  row_membership_df <- data.frame(row_memberships)
  unique_row_groups <- row_membership_df |> 
    group_by_all() |>
    summarise(COUNT = n(), .groups = 'drop') |>
    mutate(group = row_number())
  row_groups <- row_membership_df |>
    left_join(unique_row_groups, by = colnames(row_membership_df)) |>
    dplyr::select(group)

  col_membership_df <- data.frame(col_memberships)
  unique_col_groups <- col_membership_df |> 
    group_by_all() |>
    summarise(COUNT = n(), .groups = 'drop') |>
    mutate(group = row_number())
  col_groups <- col_membership_df |>
    left_join(unique_col_groups, by = colnames(col_membership_df)) |>
    dplyr::select(group)
  
  list(
    row_groups = row_groups$group,
    col_groups = col_groups$group,
    fitted_mat = NULL
  )
}

evaluate_checker <- function(checker, fitted_mat, row_groups, col_groups) {
  to_return <- list()
  to_return$row_group_count <- length(unique(row_groups))
  to_return$col_group_count <- length(unique(col_groups))

  for (metric in metrics) {
    if (length(row_groups) != length(checker$row_partition) || to_return$row_group_count == length(checker$row_partition)) {
      row_result <- -1
    } else {
      row_result <- igraph::compare(row_groups, checker$row_partition, method = metric)
    }
    if (length(col_groups) != length(checker$col_partition) || to_return$col_group_count == length(checker$col_partition)) {
      col_result <- -1
      col_result_true <- -1
    } else {
      col_result <- igraph::compare(col_groups, checker$col_partition, method = metric)
      true_feature_indices <- which(checker$true_features > 0)
      col_result_true <- igraph::compare(col_groups[true_feature_indices], 
                                         checker$col_partition[true_feature_indices],
                                         method = metric)
    }
    
    to_return[[paste(metric, "row", sep = "_")]] <- row_result
    to_return[[paste(metric, "col", sep = "_")]] <- col_result
    to_return[[paste(metric, "col_true", sep = "_")]] <- col_result_true
  }
  
  if(is.null(fitted_mat)) {
    to_return$true_err <- NA
  } else {
    to_return$true_err <- mean((checker$centers - fitted_mat)^2)
  }
  to_return
}

get_all_checker_results <- function(all_checkers, all_results, extractor) {
  all_info <- NULL
  for(run in 1:length(all_checkers)) {
    evaluated_info <- do.call(evaluate_checker,
                              c(list(checker = all_checkers[[run]]), extractor(all_results[[run]])))
    new_row <- as_tibble_row(
      c(evaluated_info,
        noise_level = all_checkers[[run]]$noise_level,
        trial = all_checkers[[run]]$trial,
        extra_dim = all_checkers[[run]]$extra_dim,
        true_row_num = length(unique(all_checkers[[run]]$row_partition)),
        true_col_num = length(unique(all_checkers[[run]]$col_partition)),
        n = length(all_checkers[[run]]$row_partition),
        p = length(all_checkers[[run]]$col_partition)
      )
    )
    if(is.null(all_info)) {
      all_info <- new_row
    } else {
      all_info <- all_info |> add_row(new_row)
    }
  }
  
  return(all_info)
}
```

# Data

```{r}
set.seed(2024)
SAVE_RESULTS = TRUE
all_checkers <- list()

trials <- 20
noise_levels <- c(3)
extra_dims <- c(0, 50, 100, 250, 500, 1000)

i <- 1
for(trial in 1:trials) {
  for (noise_level in noise_levels) {
    for (extra_dim in extra_dims) {
      all_checkers[[i]] <- gen_checkerboard(
        100,
        100,
        5,
        5,
        noise = noise_level,
        cluster_spread = 10,
        p_extra = extra_dim,
        prob_empty = 0
      )
      all_checkers[[i]]$noise_level = noise_level
      all_checkers[[i]]$extra_dim = extra_dim
      all_checkers[[i]]$trial = trial
      i <- i + 1
    }
  }
}

```

# BiCobra

```{r}
bcbc_extractor <- function(bcbc_result) {
  best_run <- bcbc_result$cv_data |> slice(which.min(eBIC2))
  best_index <- best_run$index
  list(
    row_groups = bcbc_result$row_clusters[[best_index]],
    col_groups = bcbc_result$col_clusters[[best_index]],
    fitted_mat = bcbc_result$all_runs[[best_index]]$U
  )
}

all_bcbc_results = list()
for(checker in 1:length(all_checkers)) {
  all_bcbc_results[[checker]] <-
    cv.BCBC(
      all_checkers[[checker]]$X,
      lambdas = 2 ^ seq(-5,-4, 1),
      gammas = 2 ^ seq(1, 6, 2),
      progress = FALSE,
      scale_gamma = TRUE,
      recalculate_weights = TRUE,
      tol=1e-4,
      percent_noise = 0.25
    )
  break
}

if(SAVE_RESULTS) {
  saveRDS(all_bcbc_results, paste0("./rds_files/all_bcbc_results", Sys.time(), ".RDS"))
}

bcbc_results <- get_all_checker_results(all_checkers, all_bcbc_results, bcbc_extractor)
```

# Cobra

```{r}
cobra_extractor <- function(cobra_result) {
  best_result <- which.min(cobra_result$validation_error)
  list(
    col_groups = cobra_result$groups_row[[best_result]]$cluster,
    row_groups = cobra_result$groups_col[[best_result]]$cluster,
    fitted_mat = t(cobra_result$U[[best_result]])
  )
}

all_cobra_results = list()
for(checker in 1:length(all_checkers)) {
  wts <- fast_gkn_weights(
    t(all_checkers[[checker]]$X),
    k_row = 2,
    k_col = 2,
    phi = 0.5,
    approx = 0
  )
  
  all_cobra_results[[checker]] <-
    cobra_validate(
      t(all_checkers[[checker]]$X),
      wts$E_row,
      wts$E_col,
      wts$w_row,
      wts$w_col,
      gamma = 2 ^ seq(3, 16, 0.25),
      max_iter = 500
    )
}

if(SAVE_RESULTS) {
  saveRDS(all_cobra_results, paste0("./rds_files/all_cobra_results", Sys.time(), ".RDS"))
}

cobra_results <- get_all_checker_results(all_checkers, all_cobra_results, cobra_extractor)
```

# BCEL

```{r}
bcel_extractor <- function(bcel_result) {
  to_return <- overlap_to_groups(abs(bcel_result$U) > 0, abs(bcel_result$V) > 0)
  to_return$fitted_mat <- bcel_result$U %*% t(bcel_result$V)
  return(to_return)
}

all_bcel_results = list()
for(checker in 1:length(all_checkers)) {
  all_bcel_results[[checker]] <-
    bcel_stable(
      all_checkers[[checker]]$X,
      r = 5
    )
}

if(SAVE_RESULTS) {
  saveRDS(all_bcel_results, paste0("./rds_files/all_bcel_results", Sys.time(), ".RDS"))
}
bcel_results <- get_all_checker_results(all_checkers, all_bcel_results, bcel_extractor)
```

# S4VD

```{r}
biclust_extractor <- function(biclust_obj) {
  overlap_to_groups(biclust_obj@RowxNumber, t(biclust_obj@NumberxCol))
}

all_s4vd_results = list()
for(checker in 1:length(all_checkers)) {
  all_s4vd_results[[checker]] <-
    biclust(
      all_checkers[[checker]]$X,
      method = s4vd::BCs4vd(),
      row.overlap = FALSE,
      col.overlap = FALSE,
      pcerv = 1,
      pceru = 1,
      nbiclust = 25,
      iter = 1000,
      gamm = 1,
      merr = 1e-4,
      ss.thr = c(0, 1)
    )
}

if(SAVE_RESULTS) {
  saveRDS(all_s4vd_results, paste0("./rds_files/all_s4vd_results", Sys.time(), ".RDS"))
}

s4vd_results <- get_all_checker_results(all_checkers, all_s4vd_results, biclust_extractor)
```

# SparseBC

```{r}
sparseBC_extractor <- function(sparseBC_run) {
  list(
    row_groups = sparseBC_run$Cs,
    col_groups = sparseBC_run$Ds,
    fitted_mat = sparseBC_run$mus
  )
}

run_sparsebc <- function(X, gammas) {
  lambda <- sparseBC.BIC(X,
                         5,
                         5,
                         gammas)
  
  sparsebc_fit <- sparseBC(X,
                           5,
                           5,
                           lambda$lambda)
  sparsebc_fit
}

all_sparsebc_results = list()
for(checker in 1:length(all_checkers)) {
  all_sparsebc_results[[checker]] <-
    run_sparsebc(all_checkers[[checker]]$X, gammas=2^seq(-2, 10, 1))
  break
}

if(SAVE_RESULTS) {
  saveRDS(all_sparsebc_results, paste0("./rds_files/all_sparsebc_results", Sys.time(), ".RDS"))
}

sparsebc_results <- get_all_checker_results(all_checkers, all_sparsebc_results, sparseBC_extractor)
```

# SCBiclust

```{r}
scbiclust_extractor <- function(scbiclust_result) {
  stacked_rows <- do.call(rbind, scbiclust_result$which.x)
  stacked_cols <- do.call(rbind, scbiclust_result$which.y)
  overlap_to_groups(t(stacked_rows), t(stacked_cols))
}

all_scbiclust_results = list()
for(checker in 1:length(all_checkers)) {
  all_scbiclust_results[[checker]] <-
    PermBiclust.sigclust_stop(all_checkers[[checker]]$X,
                              sc = FALSE,
                              silent = TRUE,
                              maxnum.bicluster = 5)
}

if(SAVE_RESULTS) {
  saveRDS(all_scbiclust_results, paste0("./rds_files/all_scbiclust_results", Sys.time(), ".RDS"))
}

scbiclust_results <- get_all_checker_results(all_checkers, all_scbiclust_results, scbiclust_extractor)
```

# BCPlaid

```{r}

all_bcplaid_results = list()
for (checker in 1:length(all_checkers)) {
  all_bcplaid_results[[checker]] <-
    biclust(
      all_checkers[[checker]]$X,
      method = BCPlaid(),
      background = FALSE,
      max.layers = 25,
      iter.layer = 100,
      iter.startup = 100,
      row.release = 0.7,
      col.release = 0.7,
      verbose = FALSE
    )
}

if(SAVE_RESULTS) {
  saveRDS(all_bcplaid_results, paste0("./rds_files/all_bcplaid_results", Sys.time(), ".RDS"))
}

plaid_results <- get_all_checker_results(all_checkers, all_bcplaid_results, biclust_extractor)
```

# DCT

```{r}

all_dct_results = list()
for(checker in 1:length(all_checkers)) {
  checker_dist <- dist(all_checkers[[checker]]$X)
  checker_dist_col <- dist(t(all_checkers[[checker]]$X))

  cut_tree_check <-
    cutreeDynamic(hclust(checker_dist),
                  minClusterSize = 20,
                  distM = as.matrix(checker_dist))
  
  cut_tree_check_col <-
    cutreeDynamic(hclust(checker_dist_col),
                  minClusterSize = 20,
                  distM = as.matrix(checker_dist_col))
  all_dct_results[[checker]] <- list(
    row_groups = cut_tree_check,
    col_groups = cut_tree_check_col,
    fitted_mat = NULL
  )
}

if(SAVE_RESULTS) {
  saveRDS(all_dct_results, paste0("./rds_files/all_dct_results", Sys.time(), ".RDS"))
}

all_dct_results <- get_all_checker_results(all_checkers, all_dct_results, identity)

```
