```{r}
library(tidyverse)
library(BCBC)
```

# Helper Functions

```{r}
source("./simulation_helpers.R")
```

## Generate Data

```{r}
all_checkers <- generate_checkers(2024)
```

## Results

```{r}
all_results <- bind_rows(list(
  # DTC = get_all_checker_results(
  #   all_checkers,
  #   readRDS(
  #     "~/BCBC/simulated_experiments/rds_files/all_dct_results2024-12-02 12:26:34.393905.RDS"
  #   ),
  #   dct_extractor
  # ),
  # threshold = get_all_checker_results(
  #   all_checkers,
  #   readRDS(
  #     "~/BCBC/simulated_experiments/rds_files/all_threshold_results2024-10-18 15:27:07.112123.RDS"
  #   ),
  #   dct_extractor
  # ),
  # S4VD = get_all_checker_results(
  #   all_checkers,
  #   readRDS(
  #     "~/BCBC/simulated_experiments/rds_files/all_s4vd_results2024-12-01 21:16:02.71162.RDS"
  #   ),
  #   biclust_extractor
  # ),
  `SC-Biclust` = get_all_checker_results(
    all_checkers,
    readRDS(
      "~/BCBC/simulated_experiments/rds_files/all_scbiclust_results_cv2025-01-29 01:50:34.555372.RDS"
    ),
    scbiclust_extractor
  ),
  # `SC-Biclust*` = get_all_checker_results(
  #   all_checkers,
  #   readRDS(
  #     "~/BCBC/simulated_experiments/rds_files/all_scbiclust_results2024-10-18 15:13:16.317519.RDS"
  #   ),
  #   scbiclust_extractor
  # ),
  # PLAID = get_all_checker_results(
  #   all_checkers,
  #   readRDS(
  #     "~/BCBC/simulated_experiments/rds_files/all_bcplaid_results2024-11-29 19:31:22.307164.RDS"
  #   ),
  #   biclust_extractor
  # ),
  SparseBC = get_all_checker_results(
    all_checkers,
    readRDS(
      "~/BCBC/simulated_experiments/rds_files/all_sparsebc_results_with_cv2025-02-14 06:42:11.430309.RDS"
    ),
    sparseBC_extractor
  ),
  # `SparseBC*` = get_all_checker_results(
  #   all_checkers,
  #   readRDS(
  #     "~/BCBC/simulated_experiments/rds_files/all_sparsebc_results2024-10-18 15:05:36.032485.RDS"
  #   ),
  #   sparseBC_extractor
  # ),
  # COBRA = read.csv("~/BCBC/simulated_experiments/rds_files/COBRA_25503471.csv"),
  `COBRA` = read.csv("~/BCBC/simulated_experiments/rds_files/COBRA_PREPROCESS_25503263.csv"),
  BCEL = read.csv("~/BCBC/simulated_experiments/rds_files/BCEL_25904516.csv"),
  # `Adaptive BCBC` = read.csv("~/BCBC/simulated_experiments/rds_files/BCBC_NO_SCALE_25426406.csv"),
  `Adaptive BCBC` = read.csv("~/BCBC/simulated_experiments/rds_files/BCBC_NO_SCALE_25904599.csv"),
  BCBC = read.csv("~/BCBC/simulated_experiments/rds_files/BCBC_NO_SCALE_OR_ADAPT_25904571.csv"),
  # `ANN BCBC` = read.csv("~/BCBC/simulated_experiments/rds_files/BCBC_ADAPT_APPROX_25426415.csv")
  `ANN BCBC` = read.csv("~/BCBC/simulated_experiments/rds_files/BCBC_ADAPT_APPROX_25904598.csv")
),
.id = "algorithm")

```

```{r}

color_scheme = c(`Adaptive BCBC` = "#01498a",
                 `ANN BCBC` = "#0061b8",
                 `BCBC` = "#0083f7",
                 `COBRA` = "#e31a1c",
                 `COBRA*` = "#e31a1c",
                 `SparseBC` = "#ff7f00",
                 `SparseBC*` = "#ff7f00",
                 `BCEL` = "#b2008a",
                 `SC-Biclust` = "#33a02c",
                 `SC-Biclust*` = "#33a02c",
                 `DTC` = "#fdbf6f",
                 `PLAID` = "#fb9a99",
                 `S4VD` = "#b2df8a")

se_filtered <- function(vals) {
  vals <- vals[is.finite(vals)]
  sd(vals) / sqrt(length(vals))
}

se <- function(vals) {
  sd(vals) / sqrt(length(vals))
}

mean_filtered <- function(vals) {
  mean(vals[is.finite(vals)])
}

all_results <- all_results |>
  mutate(
    adjusted.rand_row = pmax(0, adjusted.rand_row),
    adjusted.rand_col_true = pmax(0, adjusted.rand_col_true),
    adjusted.rand_col = pmax(0, adjusted.rand_col),
    adjusted.rand_bicluster = pmax(0, adjusted.rand_bicluster),
    adjusted.rand_bicluster_true = pmax(0, adjusted.rand_bicluster_true),
    adjusted.rand_bicluster_harmonic = 2 * ( adjusted.rand_bicluster * adjusted.rand_bicluster_true) / (adjusted.rand_bicluster + adjusted.rand_bicluster_true),
    adjusted.rand_bicluster_harmonic = ifelse(is.nan(adjusted.rand_bicluster_harmonic), 0, adjusted.rand_bicluster_harmonic)
  ) |>
  relocate(adjusted.rand_bicluster_harmonic, .after = adjusted.rand_bicluster_true)
  
squash_trials <- all_results |>
  group_by(p, algorithm) |>
  summarise(across(feature_recall:col_ch, list(mean=mean, se=se)))

plot_methods <- function(metric, label=metric) {
  ggplot(squash_trials, aes(x=p - 200, y=.data[[paste0(metric, "_mean")]], color=algorithm)) +
  geom_ribbon(aes(ymin = .data[[paste0(metric, "_mean")]] - 1.96 * .data[[paste0(metric, "_se")]],
                  ymax = .data[[paste0(metric, "_mean")]] + 1.96 * .data[[paste0(metric, "_se")]],
                  fill = algorithm),
              alpha = 0.20, linetype = "blank") + 
  geom_line(linewidth=1) +
  geom_point(size=2.5) +
  labs(y = label, x = "Extra Noisy Features", color="Algorithm", fill="Algorithm") + 
  scale_fill_manual(values = color_scheme) +
  scale_color_manual(values = color_scheme) +
  scale_x_continuous(breaks = seq(0, 900, 100)) + 
  theme_minimal()
}

# plot_methods("adjusted.rand_row", "Row ARI")
# ggsave("~/BCBC/simulated_experiments/figures/row_ari.png")

# plot_methods("adjusted.rand_col_true", "True Column ARI")
# ggsave("~/BCBC/simulated_experiments/figures/true_col_ari.png")

# plot_methods("adjusted.rand_col", "All Column ARI")
# ggsave("~/BCBC/simulated_experiments/figures/col_ari.png")

plot_methods("feature_f1", "F1 Score")
# ggsave("~/BCBC/simulated_experiments/figures/simulation1_true_bicluster_ari.png")
```

```{r}
ggplot(squash_trials |> filter(
  algorithm %in% c("DTC", "S4VD", "SC-Biclust", "PLAID",
                   "SparseBC", "COBRA", "BCEL", "Adaptive BCBC",
                   "BCBC", "ANN BCBC")
), aes(x=p - 200, y=.data[[paste0("adjusted.rand_bicluster_true", "_mean")]], color=algorithm)) +
  geom_ribbon(aes(ymin = .data[[paste0("adjusted.rand_bicluster_true", "_mean")]] - 1.96 * .data[[paste0("adjusted.rand_bicluster_true", "_se")]],
                  ymax = .data[[paste0("adjusted.rand_bicluster_true", "_mean")]] + 1.96 * .data[[paste0("adjusted.rand_bicluster_true", "_se")]],
                  fill = algorithm),
              alpha = 0.20, linetype = "blank") + 
  geom_line(linewidth=1) +
  geom_point(size=2.5) +
  labs(y = "True Bicluster ARI", x = "Extra Noisy Features", color="Algorithm", fill="Algorithm") + 
  scale_fill_manual(values = color_scheme) +
  scale_color_manual(values = color_scheme) +
  scale_x_continuous(breaks = seq(0, 900, 100)) + 
  ggtitle("Comparison of Biclustering Performance") +
  theme_minimal()

# ggsave("~/BCBC/simulated_experiments/figures/simulation1_basic_true_bicluster_ari.pdf", device = "pdf",
#        units = "in",
#        width = 8,
#        height = 6)

```


```{r}
ggplot(squash_trials |> filter(
  algorithm %in% c("DTC", "SC-Biclust*",
                   "SparseBC*", "COBRA*", "Adaptive BCBC",
                   "ANN BCBC")
), aes(x=p - 200, y=.data[[paste0("adjusted.rand_bicluster_true", "_mean")]], color=algorithm)) +
  geom_ribbon(aes(ymin = .data[[paste0("adjusted.rand_bicluster_true", "_mean")]] - 1.96 * .data[[paste0("adjusted.rand_bicluster_true", "_se")]],
                  ymax = .data[[paste0("adjusted.rand_bicluster_true", "_mean")]] + 1.96 * .data[[paste0("adjusted.rand_bicluster_true", "_se")]],
                  fill = algorithm),
              alpha = 0.20, linetype = "blank") + 
  geom_line(linewidth=1) +
  geom_point(size=2.5) +
  labs(y = "True Bicluster ARI", x = "Extra Noisy Features", color="Algorithm", fill="Algorithm") + 
  scale_fill_manual(values = color_scheme) +
  scale_color_manual(values = color_scheme) +
  scale_x_continuous(breaks = seq(0, 900, 100)) + 
  scale_y_continuous(breaks = seq(0, 1, 0.25)) + 
  ggtitle("Comparison of Strongest Methods with Oracle Information") +
  theme_minimal()

```

```{r}
ggplot(all_results |>
         filter(grepl("BCBC", algorithm) | 
                  grepl("COBRA", algorithm) | 
                  grepl("SparseBC", algorithm) | 
                  grepl("SC-Biclust", algorithm) |
                  grepl("BCEL", algorithm)) |>
         filter(p > 200),
       aes(x=factor(p - 200), y=feature_auc, color=algorithm)) +
  geom_boxplot(coef = 1.25) +
  labs(y = "AUC Score", x = "Extra Noisy Features", color="Algorithm") + 
  scale_color_manual(values = color_scheme) +
  ggtitle("AUC of Feature Selection Mechanism") +
  theme_minimal() +
  annotate("segment", x = seq(0.5, 9.5, 1), xend = seq(0.5, 9.5, 1),
           y = 0, yend = 1,
           color = "grey", linewidth = 0.25, linetype="dashed") +
  theme(panel.grid.major.x = element_blank())

# ggsave("~/BCBC/simulated_experiments/figures/simulation1_auc.pdf", device = "pdf",
#        units = "in",
#        width = 9,
#        height = 5)
```

```{r}
ggplot(all_results |>
         filter(grepl("BCBC", algorithm) | 
                  grepl("COBRA", algorithm) | 
                  grepl("SparseBC", algorithm) | 
                  grepl("SC-Biclust", algorithm) |
                  grepl("BCEL", algorithm)) |>
         filter(p > 200),
       # aes(x=factor(p - 200), y=feature_auc, color=algorithm)) +
       aes(x=algorithm, y=feature_auc, color=factor(p, ordered = T))) +
  geom_boxplot(coef = 1.25, outlier.size = 0.75) +
  labs(y = "AUC Score", x = "Extra Noisy Features", color="Algorithm") + 
  # scale_color_manual(values = color_scheme) +
  scale_color_manual(
    values = gray.colors(n = 9, start = 0.5, end = 0.05)
  ) +
  ggtitle("AUC of Feature Selection Mechanism") +
  theme_minimal() +
  annotate("segment", x = seq(0.5, 7.5, 1), xend = seq(0.5, 7.5, 1),
           y = 0.4, yend = 1,
           color = "grey", linewidth = 0.25, linetype="dashed") +
  theme(panel.grid.major.x = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1.25, hjust = 1))

# ggsave("~/BCBC/simulated_experiments/figures/simulation1_auc.pdf", device = "pdf",
#        units = "in",
#        width = 9,
#        height = 5)
```

```{r}
ggplot(all_results |>
         filter(grepl("BCBC", algorithm) | 
                  grepl("COBRA", algorithm) | 
                  grepl("SparseBC", algorithm) | 
                  grepl("SC-Biclust", algorithm) |
                  grepl("BCEL", algorithm)) |>
         filter(p > 200),
       aes(x=factor(p - 200), y=feature_auc, color=algorithm)) +
  geom_boxplot(coef = 1.25, outlier.size = 0.75) +
  labs(y = "AUC Score", x = "Extra Noisy Features", color="Algorithm") + 
  scale_color_manual(values = color_scheme, guide = "none") +
  ggtitle("AUC of Feature Selection Mechanism") +
  theme_minimal() +
  scale_x_discrete(breaks = seq(100, 900, 100),
                   labels = c(100, "", 300, "", 500, "", 700, "", 900)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1.25, vjust = 1.4, size = 7),
        panel.spacing = unit(c(0.7), "lines")) +
  facet_wrap(~algorithm, ncol = 7)

ggsave("~/BCBC/simulated_experiments/figures/simulation1_auc.pdf", device = "pdf",
       units = "in",
       width = 9,
       height = 5)
```

# SNR Experiments

```{r}
all_checkers_SNR <- generate_checkers_SNR(2024)
```

```{r}
all_results_SNR <- bind_rows(list(
  # DTC = get_all_checker_results(
  #   all_checkers,
  #   readRDS(
  #     "~/BCBC/simulated_experiments/rds_files/all_dct_results2024-10-25 19:05:42.938786.RDS"
  #   ),
  #   dct_extractor
  # ),
  # threshold = get_all_checker_results(
  #   all_checkers,
  #   readRDS(
  #     "~/BCBC/simulated_experiments/rds_files/all_threshold_results2024-10-18 15:27:07.112123.RDS"
  #   ),
  #   dct_extractor
  # ),
  # S4VD = get_all_checker_results(
  #   all_checkers,
  #   readRDS(
  #     "~/BCBC/simulated_experiments/rds_files/all_s4vd_results2024-10-18 14:28:38.089409.RDS"
  #   ),
  #   biclust_extractor
  # ),
  `SC-Biclust` = get_all_checker_results(
    all_checkers_SNR,
    readRDS(
      "~/BCBC/simulated_experiments/rds_files/all_scbiclust_results_SNR2024-11-30 22:58:21.169365.RDS"
    ),
    scbiclust_extractor
  ),
  # PLAID = get_all_checker_results(
  #   all_checkers,
  #   readRDS(
  #     "~/BCBC/simulated_experiments/rds_files/all_bcplaid_results2024-10-18 15:53:21.090657.RDS"
  #   ),
  #   biclust_extractor
  # ),
  SparseBC = get_all_checker_results(
    all_checkers_SNR,
    readRDS(
      "~/BCBC/simulated_experiments/rds_files/all_sparsebc_results_SNR2024-12-01 04:41:34.637185.RDS"
    ),
    sparseBC_extractor
  ),
  # COBRA = read.csv("~/BCBC/simulated_experiments/rds_files/COBRA_18439720.csv"),
  # BCEL = read.csv("~/BCBC/simulated_experiments/rds_files/BCEL_18588917.csv"),
  `Adaptive BCBC` = read.csv("~/BCBC/simulated_experiments/rds_files/BCBC_NO_SCALE_25383242_SNR.csv"),
  BCBC = read.csv("~/BCBC/simulated_experiments/rds_files/BCBC_NO_SCALE_OR_ADAPT_25383247_SNR.csv"),
  `ANN BCBC` = read.csv("~/BCBC/simulated_experiments/rds_files/BCBC_ADAPT_APPROX_25383249_SNR.csv")
),
.id = "algorithm")
```


```{r}

all_results_SNR <- all_results_SNR |>
  mutate(
    adjusted.rand_row = pmax(0, adjusted.rand_row),
    adjusted.rand_col = pmax(0, adjusted.rand_col),
    adjusted.rand_col_true = pmax(0, adjusted.rand_col_true),
    adjusted.rand_bicluster_true = pmax(0, adjusted.rand_bicluster_true),
    adjusted.rand_bicluster = pmax(0, adjusted.rand_bicluster),
    adjusted.rand_bicluster_harmonic = 2 * ( adjusted.rand_bicluster * adjusted.rand_bicluster_true) / (adjusted.rand_bicluster + adjusted.rand_bicluster_true),
    adjusted.rand_bicluster_harmonic = ifelse(is.nan(adjusted.rand_bicluster_harmonic), 0, adjusted.rand_bicluster_harmonic)
  ) |>
  relocate(adjusted.rand_bicluster_harmonic, .after = adjusted.rand_bicluster_true)
  

squash_trials_SNR <- all_results_SNR |>
  group_by(p, noise_level, n, algorithm) |>
  summarise(across(feature_recall:col_ch, list(mean=mean, se=se))) |> 
  ungroup()

squash_trials_SNR <- squash_trials_SNR |> 
  group_by(p, noise_level, n) |>
  mutate(is_highest_bicluster_ari = adjusted.rand_bicluster_mean == max(adjusted.rand_bicluster_mean)) |> 
  mutate(is_highest_true_bicluster_ari = adjusted.rand_bicluster_true_mean == max(adjusted.rand_bicluster_true_mean)) |>
  mutate(is_highest_harmonic_bicluster_ari = adjusted.rand_bicluster_harmonic_mean == max(adjusted.rand_bicluster_harmonic_mean))
  

```

```{r}

sim2_ari <- ggplot(squash_trials_SNR, aes(x = factor(n), y = factor(noise_level))) +
  geom_tile(aes(fill = adjusted.rand_bicluster_true_mean)) +
  geom_text(aes(label = round(adjusted.rand_bicluster_true_mean, digits = 3),
                fontface = ifelse(is_highest_true_bicluster_ari, "bold", "plain")),
            size=ifelse(squash_trials_SNR$is_highest_true_bicluster_ari, 4, 3.5),
            color = "#000") +
  geom_text(aes(label = paste0("(", round(adjusted.rand_bicluster_true_se, digits = 3), ")")), 
            nudge_y = -0.30,
            size = 2.5,
            color = "#000") +
  labs(x = "Number of rows and informative columns", y = "Noise Level", fill="True Bicluster ARI") +
  scale_fill_viridis_c(breaks=seq(0, 1, 0.2), limits = c(0,1), option = "E") +
  facet_wrap(~algorithm) +
  theme_minimal() +
  ggtitle("Comparison of Methods in High-Noise Regime") +
  theme(legend.position = c(0.9, 0.02),
        legend.justification = c(1, 0), 
        legend.text = element_text(size=12),
        legend.key.height=unit(1,"cm"),
        strip.text.x = element_text(size = 10, colour = "black"),
        strip.background = element_rect(fill="#DDD", linewidth = 0))

ggsave("~/BCBC/simulated_experiments/figures/simulation2_true_ari.pdf",
       plot=sim2_ari,
       units = "in",
       width = 9,
       height = 6,
       device = "pdf")

```

```{r}
input_df <- all_results_SNR |>
         filter(grepl("BCBC", algorithm) | grepl("SparseBC", algorithm) | grepl("SC-", algorithm))

sim2_auc = ggplot(input_df,
       aes(x=factor(n), y=feature_auc, color=algorithm)) +
       # aes(x=algorithm, y=feature_auc, color=algorithm, group = factor(paste(noise_level, algorithm)))) +
  geom_boxplot() +
  labs(y = "AUC Score", x = "Number of rows and informative columns", color = "Algorithm") + 
  scale_color_manual(values = color_scheme) +
  # facet_wrap(~noise_level_label, labeller = label_tex) +
  facet_wrap(~noise_level, labeller = labeller(noise_level = ~ paste0("Noise Level=", .x))) +
  ggtitle("AUC of Feature Selection Mechanism") +
  theme_minimal() +
  theme(legend.position = c(0.92, 0.0),
        legend.justification = c(1, 0), 
        legend.text = element_text(size=12),
        legend.key.height=unit(1,"cm"),
        strip.text.x = element_text(size = 10, colour = "black"),
        strip.background = element_rect(fill="#DDD", linewidth = 0),
        panel.grid.major.x = element_blank()) +
  annotate("segment", x = seq(0.5, 5.5, 1), xend = seq(0.5, 5.5, 1),
           y = 0, yend = 1,
           color = "grey", linewidth = 0.25, linetype="dashed")

ggsave("~/BCBC/simulated_experiments/figures/simulation2_auc.pdf",
       plot=sim2_auc,
       units = "in",
       width = 8,
       height = 6,
       device = "pdf")


```
