```{r}
library(tidyverse)
library(BCBC)
library(dynamicTreeCut)
library(sparseBC)
library(s4vd)
library(biclust)
library(SCBiclust)
library(future.apply)

# install.packages("../BCEL", repos = NULL, type="source")
# library(BCEL)  # https://github.com/SamGRosen/BCEL, need to compile from source

plan(sequential, split=TRUE)
```

# Data

```{r}
SAVE_RESULTS = TRUE
all_checkers <- generate_checkers(2024)
```

# S4VD

```{r}
all_s4vd_results = list()
for(checker in 1:length(all_checkers)) {
  print(c(checker, as.character(Sys.time())))

  all_s4vd_results[[checker]] <-
    biclust(
      all_checkers[[checker]]$X,
      method = s4vd::BCs4vd(),
      row.overlap = FALSE,
      col.overlap = FALSE,
      pcerv = 1,
      pceru = 1,
      nbiclust = 25,
      row.min = min(table(all_checkers[[checker]]$row_partition)),
      col.min = min(table(all_checkers[[checker]]$col_partition)),
      iter = 1000,
      gamm = 1,
      merr = 1e-4,
      start.iter = 20,
      ss.thr = c(0, 1)
    )
}

if(SAVE_RESULTS) {
  saveRDS(all_s4vd_results, paste0("./rds_files/all_s4vd_results", Sys.time(), ".RDS"))
}
```

# SparseBC

```{r}
run_sparsebc <- function(X, gammas) {
    kr <-
    sparseBC.choosekr(
      X,
      k = 3:6,
      r = 3:6,
      lambda = 0,
      percent = 0.125,
      TRUE
    )

  print(kr)

  if(is.null(kr$estimated_kr)) {
    best_k <- kr$bestK
    best_r <- kr$bestR
  } else {
    best_k <- kr$estimated_kr[1, 1]
    best_r <- kr$estimated_kr[1, 2]
  }
  
  lambda <- sparseBC.BIC(X,
                         best_k,
                         best_r,
                         gammas)
  
  sparsebc_fit <- sparseBC(X,
                           best_k,
                           best_r,
                           lambda$lambda)
  sparsebc_fit
}

all_sparsebc_results = list()
for(checker in 1:66) {
  print(c(checker, as.character(Sys.time())))

  all_sparsebc_results[[checker]] <-
    run_sparsebc(all_checkers[[checker]]$X, gammas=2^seq(-2, 12, 1))
}

if(SAVE_RESULTS) {
  saveRDS(all_sparsebc_results, paste0("./rds_files/all_sparsebc_results_with_cv", Sys.time(), ".RDS"))
}
```

# SCBiclust

```{r}
# all_scbiclust_results = list()
# for(checker in 1:length(all_checkers)) {
#   print(c(checker, as.character(Sys.time())))
# 
#   all_scbiclust_results[[checker]] <-
#     PermBiclust.sigclust_stop(all_checkers[[checker]]$X,
#                               sc = FALSE,
#                               silent = TRUE,
#                               maxnum.bicluster = 6)
# }

if(SAVE_RESULTS) {
  saveRDS(all_scbiclust_results, paste0("./rds_files/all_scbiclust_results_cv", Sys.time(), ".RDS"))
}

```

# BCPlaid

```{r}

all_bcplaid_results = list()
for (checker in 1:length(all_checkers)) {
  print(c(checker, as.character(Sys.time())))

  all_bcplaid_results[[checker]] <-
    biclust(
      all_checkers[[checker]]$X,
      method = BCPlaid(),
      background = FALSE,
      max.layers = 25,
      iter.layer = 200,
      iter.startup = 200,
      row.release = 0.3,
      col.release = 0.3,
      verbose = FALSE
    )
  
  if(length(all_bcplaid_results[[checker]]@RowxNumber) == 1) {
    print(checker)
    all_bcplaid_results[[checker]] <-
      biclust(
        all_checkers[[checker]]$X,
        method = BCPlaid(),
        background = FALSE,
        max.layers = 25,
        iter.layer = 400,
        iter.startup = 400,
        row.release = 0.1,
        col.release = 0.1,
        verbose = FALSE
      )
  }
  
  if(length(all_bcplaid_results[[checker]]@RowxNumber) == 1) {
    print(checker)
    all_bcplaid_results[[checker]]@RowxNumber <- matrix(TRUE, 
                                                        nrow = nrow(all_checkers[[checker]]$X), 
                                                        ncol = 1)
    all_bcplaid_results[[checker]]@NumberxCol <- matrix(TRUE, 
                                                    nrow = 1, 
                                                    ncol = ncol(all_checkers[[checker]]$X))
  }
}

if(SAVE_RESULTS) {
  saveRDS(all_bcplaid_results, paste0("./rds_files/all_bcplaid_results", Sys.time(), ".RDS"))
}
```

# DCT

```{r}

all_dct_results = list()
for(checker in 1:length(all_checkers)) {
  print(c(checker, as.character(Sys.time())))

  checker_dist <- dist(all_checkers[[checker]]$X)
  checker_dist_col <- dist(t(all_checkers[[checker]]$X))

  cut_tree_check <-
    cutreeDynamic(hclust(checker_dist),
                  minClusterSize = min(table(all_checkers[[checker]]$row_partition)),
                  distM = as.matrix(checker_dist))
  
  cut_tree_check_col <-
    cutreeDynamic(hclust(checker_dist_col),
                  minClusterSize = min(table(all_checkers[[checker]]$col_partition)),
                  distM = as.matrix(checker_dist_col))
  all_dct_results[[checker]] <- list(
    row_groups = cut_tree_check,
    col_groups = cut_tree_check_col,
    fitted_mat = NULL
  )
}

if(SAVE_RESULTS) {
  saveRDS(all_dct_results, paste0("./rds_files/all_dct_results", Sys.time(), ".RDS"))
}
```


# Manual Threshold


```{r}

all_threshold_results = list()
for(checker in 1:length(all_checkers)) {
  print(c(checker, as.character(Sys.time())))
  row_dist <- dist(all_checkers[[checker]]$X)
  row_threshold <- get_threshold_for_k_components(
    row_dist,
    k = 5,
    max_threshold = max(row_dist),
    maxiter = 100
  )
  
  col_dist <- dist(t(all_checkers[[checker]]$X))
  col_threshold <- get_threshold_for_k_components(
    col_dist,
    k = 5,
    max_threshold = max(col_dist),
    maxiter = 100
  )

  row_groups <- dbscan::comps(dbscan::frNN(row_dist, row_threshold, sort = F))
  col_groups <- dbscan::comps(dbscan::frNN(col_dist, row_threshold, sort = F))
  all_threshold_results[[checker]] <- list(
    row_groups = row_groups,
    col_groups = col_groups,
    fitted_mat = NULL
  )
}

if(SAVE_RESULTS) {
  saveRDS(all_threshold_results, paste0("./rds_files/all_threshold_results", Sys.time(), ".RDS"))
}
```
