```{r}
lym = read.csv("./data/lymphoma_labelled.txt", header = TRUE, sep = ",")
X <- t(lym)
labels = case_when(grepl("DLCL", colnames(lym)) ~ 1,
                   grepl("FL", colnames(lym)) ~ 2,
                   grepl("CLL", colnames(lym)) ~ 3)

gene_names = read.csv("~/figure1.cdt.txt", header = TRUE, sep = "\t")
```

```{r}
bcbc_obj <- readRDS("/cwork/sgr26/BCBC_ADAPTIVE_lym2_25964044.RDS")

```

```{r}

best_lambdas <- bcbc_obj$lambda_cv$cv_data |>
  filter(is.finite(eBIC)) |>
  arrange(eBIC2) |>
  head()

best_lambda_index <- best_lambdas[1, "param_index"]
fit <- bcbc_obj$lambda_cv$all_runs[[best_lambda_index]]
# fit <- cv_obj$lambda_cv$all_runs[[2]]


plot(sort(fit$w))
plot_fit(bcbc_result_to_df(fit, labels = labels), weight_annotation = T)
# plot_fit(bcbc_result_to_df(fit, filter_weight = 0, labels = labels))
plot_fit(bcbc_result_to_df(fit, filter_weight = 0, labels = labels), bin_scale = 10)
plot_fit(bcbc_result_to_df(fit, filter_weight = 3e-4, labels = labels))
```

```{r}
top_k_indices <- function(vec, k) {
  order(vec, decreasing = TRUE)[1:k]
}


top_100_weights = top_k_indices(fit$w, 100)
top_100_missing = top_k_indices(apply(X, 2, function(w) { sum(is.na(w))}), 100)
# 
# gene_names$NAME[intersect(top_100_weights, top_100_missing)]
# 
gene_names$NAME[top_k_indices(fit$w, 50)]


table(bcbc_obj$lambda_cv$col_clusters[[best_lambdas[1, "index"]]][top_k_indices(fit$w, 500)])
```

```{r}
survival = read.csv("~/DLCL_survival_IPI.txt", header = TRUE, sep = "\t")
all_DLCL = colnames(lym)[grepl("DLCL", colnames(lym))]

DLCL_table = tibble(
  DLCL.Sample.Identifier = all_DLCL,
  cluster = bcbc_obj$lambda_cv$row_clusters[[best_lambdas[1, "index"]]][labels == 1]
) |>
  inner_join(survival, by = "DLCL.Sample.Identifier")

```

```{r}

col_clusters = bcbc_obj$lambda_cv$col_clusters[[best_lambdas[1, "index"]]]

col_clusters_w_weights = tibble(
  weight = fit$w,
  cluster = col_clusters
) |>
  arrange(-weight) |>
  mutate(index = row_number())

cluster_info = col_clusters_w_weights |> group_by(cluster) |>
  summarise(
    n = n(),
    mean = mean(weight),
    mean_norm = mean(weight) * 4026,
    sum = sum(weight),
    max = max(weight),
    max_norm = max(weight) * 4026,
    index = first(index)
  )

sample_genes = gene_names$NAME[(cluster_info |> arrange(max))$index[1:10]]

top_cluster_genes1 = which(col_clusters == 128)
top_cluster_genes2 = which(col_clusters == 120)
top_cluster_genes3 = which(col_clusters == 60)
top_cluster_genes4 = which(col_clusters == 18)
top_cluster_genes5 = which(col_clusters == 134)
top_cluster_genes6 = which(col_clusters == 27)
top_cluster_genes7 = which(col_clusters == 21)
top_cluster_genes8 = which(col_clusters == 209)
top_cluster_genes9 = which(col_clusters == 123)
top_cluster_genes10 = which(col_clusters == 17)
```

```{r}

method = "single"
plot_df <- bcbc_result_to_df(fit, labels = labels, cluster_with_weights = F, method=method)


top_cluster_cols1 = plot_df |> filter(col_num %in% top_cluster_genes1)
top_cluster_cols2 = plot_df |> filter(col_num %in% top_cluster_genes2)
top_cluster_cols3 = plot_df |> filter(col_num %in% top_cluster_genes3)
top_cluster_cols4 = plot_df |> filter(col_num %in% top_cluster_genes4)
top_cluster_cols5 = plot_df |> filter(col_num %in% top_cluster_genes5)
top_cluster_cols6 = plot_df |> filter(col_num %in% top_cluster_genes6)
top_cluster_cols7 = plot_df |> filter(col_num %in% top_cluster_genes7)
top_cluster_cols8 = plot_df |> filter(col_num %in% top_cluster_genes8)
top_cluster_cols9 = plot_df |> filter(col_num %in% top_cluster_genes9)
top_cluster_cols10 = plot_df |> filter(col_num %in% top_cluster_genes10)


fill_attr = "value"
bin_scale = 100

w_vals = sqrt(fit$w^2 + fit$lambda * fit$w)
matrix <- sweep(fit$U, 2, fit$w, "*")

row_dist <- dist(matrix)
col_dist <- as.matrix(dist(t(fit$U)))

h_row <- hclust(row_dist)

col_dist <- col_dist # - min(col_dist[col_dist > 0])
diag(col_dist) <- 0 
col_hclust <- hclust(as.dist(col_dist), method = method)
col_hclust_data <- dendro_data(col_hclust, type = "rectangle")

label_annotation <- annotate(
  geom = "rect",
  xmin = -max(plot_df$order_col) / 25,
  xmax = 0,
  ymin = plot_df$order_row - 0.5,
  ymax = plot_df$order_row + 0.5,
  fill = case_when(
    plot_df$label == 1 ~ "#11DDDD",
    plot_df$label == 2 ~ "green",
    plot_df$label == 3 ~ "yellow"
  )
)

raster <- geom_raster(aes(fill = .data[[fill_attr]]))
if (!bin_scale) {
  plot_scale = scale_fill_gradient2()
} else {
  plot_scale = scale_fill_steps2(n.breaks = bin_scale)
}

bicluster_annotation = annotate(
  "rect",
  xmin = c(min(top_cluster_cols6$order_col), min(top_cluster_cols5$order_col),
           min(top_cluster_cols4$order_col), min(top_cluster_cols3$order_col),
           min(top_cluster_cols2$order_col), min(top_cluster_cols1$order_col), # combining 1 and 2 since split
           min(top_cluster_cols7$order_col), min(top_cluster_cols8$order_col),
           min(top_cluster_cols9$order_col), min(top_cluster_cols10$order_col)),
  xmax = c(max(top_cluster_cols6$order_col), max(top_cluster_cols5$order_col),
           max(top_cluster_cols4$order_col), max(top_cluster_cols3$order_col),
           max(top_cluster_cols2$order_col), max(top_cluster_cols1$order_col),
           max(top_cluster_cols7$order_col), max(top_cluster_cols8$order_col),
           max(top_cluster_cols9$order_col), max(top_cluster_cols10$order_col)),
  ymin = 0.5,
  ymax = 62.5,
  fill = NA,
  color = "black", # scale_fill_gradient2(low="#FFC300", high="#581845")$palette(seq(0, 1, length.out = 10)),
  linewidth = 0.5,
  linetype = "twodash"
)

y_start = max(plot_df$order_row) + 1

max(top_cluster_cols1$order_col) - min(top_cluster_cols1$order_col) - length(unique(top_cluster_cols1$order_col))
max(top_cluster_cols2$order_col) - min(top_cluster_cols2$order_col) - length(unique(top_cluster_cols2$order_col))
max(top_cluster_cols3$order_col) - min(top_cluster_cols3$order_col) - length(unique(top_cluster_cols3$order_col))
max(top_cluster_cols4$order_col) - min(top_cluster_cols4$order_col) - length(unique(top_cluster_cols4$order_col))
max(top_cluster_cols5$order_col) - min(top_cluster_cols5$order_col) - length(unique(top_cluster_cols5$order_col))
max(top_cluster_cols6$order_col) - min(top_cluster_cols6$order_col) - length(unique(top_cluster_cols6$order_col))
max(top_cluster_cols7$order_col) - min(top_cluster_cols7$order_col) - length(unique(top_cluster_cols7$order_col))
max(top_cluster_cols8$order_col) - min(top_cluster_cols8$order_col) - length(unique(top_cluster_cols8$order_col))
max(top_cluster_cols9$order_col) - min(top_cluster_cols9$order_col) - length(unique(top_cluster_cols9$order_col))
max(top_cluster_cols10$order_col) - min(top_cluster_cols10$order_col) - length(unique(top_cluster_cols10$order_col))
```


```{r}
ggplot(plot_df, aes(x = order_col, y = order_row)) +
  raster +
  label_annotation +
  plot_scale +
  geom_segment(data = segment(col_hclust_data), 
               aes(x = x, y = y_start + y / max(y) * 20, xend = xend, yend = y_start + yend / max(yend) * 20)
  ) +
  bicluster_annotation +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    plot.title = element_text(size=20)
  ) +
  guides(fill = "none") +
  xlab("mRNA Sample") +
  ylab("cDNA Clone") +
  ggtitle("Lymphoma Biclustering")
```

```{r}
gene_names$NAME[top_cluster_genes1[order(-fit$w[top_cluster_genes1])][1]]
gene_names$NAME[top_cluster_genes2[order(-fit$w[top_cluster_genes2])][1]]
gene_names$NAME[top_cluster_genes3[order(-fit$w[top_cluster_genes3])][1]]
gene_names$NAME[top_cluster_genes4[order(-fit$w[top_cluster_genes4])][1]]
gene_names$NAME[top_cluster_genes5[order(-fit$w[top_cluster_genes5])][1]]
gene_names$NAME[top_cluster_genes6[order(-fit$w[top_cluster_genes6])][1]]
gene_names$NAME[top_cluster_genes7[order(-fit$w[top_cluster_genes7])][1]]
gene_names$NAME[top_cluster_genes8[order(-fit$w[top_cluster_genes8])][1]]
gene_names$NAME[top_cluster_genes9[order(-fit$w[top_cluster_genes9])][1]]
gene_names$NAME[top_cluster_genes10[order(-fit$w[top_cluster_genes10])][1]]


genes = c(top_cluster_genes1[order(-fit$w[top_cluster_genes1])][1],
          top_cluster_genes1[order(-fit$w[top_cluster_genes2])][1],
          top_cluster_genes1[order(-fit$w[top_cluster_genes3])][1],
          top_cluster_genes1[order(-fit$w[top_cluster_genes4])][1],
          top_cluster_genes1[order(-fit$w[top_cluster_genes5])][1],
          top_cluster_genes1[order(-fit$w[top_cluster_genes6])][1],
          top_cluster_genes1[order(-fit$w[top_cluster_genes7])][1],
          top_cluster_genes1[order(-fit$w[top_cluster_genes8])][1],
          top_cluster_genes1[order(-fit$w[top_cluster_genes9])][1],
          top_cluster_genes1[order(-fit$w[top_cluster_genes10])][1])
```
